### list
GET http://127.0.0.1:9129/list?app=app1&env=dev&ns=public

### update-1
POST http://127.0.0.1:9129/update?app=app1&env=dev&ns=public
Content-Type: application/json

{
  "ipman.a": "key11",
  "ipman.b": "key2",
  "ipman.c": "key3"
}

### update-2
POST http://127.0.0.1:9129/update?app=app1&env=dev&ns=public
Content-Type: application/json

{
  "ipman.a": "key100",
  "ipman.b": "key200",
  "ipman.c": "key300"
}

### version
GET http://127.0.0.1:9129/version?app=app1&env=dev&ns=public