server:
  port: 9129

spring:
  application:
    name: config-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/config_man?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password:

#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:h2db
#    username: root
#    password: 123456
#  sql:
#    init:
#      schema-locations: classpath:db.sql
#      mode: always
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true

logging:
  level:
    root: info
    org.springframework.jdbc: debug
    cn.ipman.config: debug

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl